- name: Install Need Package
  community.general.apk:
    update_cache: false
    name:
      - gitea
    state: installed

- name: Start Gitea
  ansible.builtin.service:
    name: gitea
    state: started
    enabled: true
