---
# Proxmox NFS Mount Configuration

# TrueNAS Server IP
truenas_ip: "192.168.2.10"

# NFS Mount Points Configuration
nfs_mounts:
  - name: "postgresql"
    mount_origin: "/mnt/Data/postgresql"
    mount_point: "/mnt/postgresql"
    description: "PostgreSQL WAL Archive"

  - name: "git"
    mount_origin: "/mnt/Data/git"
    mount_point: "/mnt/git"
    description: "Git Repositories"

  - name: "gitlarge"
    mount_origin: "/mnt/Data/gitlarge"
    mount_point: "/mnt/gitlarge"
    description: "Git LFS Storage"
 
  - name: "objectstorage"
    mount_origin: "/mnt/Data/objectstorage"
    mount_point: "/mnt/objectstorage"
    description: "Object Storage"
  
  - name: "mongodb"
    mount_origin: "/mnt/Data/mongodb"
    mount_point: "/mnt/mongodb"
    description: "Mongo DB"

  - name: "observability"
    mount_origin: "/mnt/Data/observability"
    mount_point: "/mnt/observability"
    description: "Observability"

  - name: "artifact"
    mount_origin: "/mnt/Data/artifact"
    mount_point: "/mnt/artifact"
    description: "artifact"

ca: "MIIB0DCCAXagAwIBAgIQcP1juIh+nMl7PYdqptT3zzAKBggqhkjOPQQDAjAyMRMwEQYDVQQKEwpIb21lTGFiIENBMRswGQYDVQQDExJIb21lTGFiIENBIFJvb3QgQ0EwHhcNMjYwNzA0MDgyMDM2WhcNMzYwNzAxMDgyMDM2WjA6MRMwEQYDVQQKEwpIb21lTGFiIENBMSMwIQYDVQQDExpIb21lTGFiIENBIEludGVybWVkaWF0ZSBDQTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABHRSPUUAZ3i/2PAJTZDIiBfdB4braJ/PPzwV84Egf2xgPEGOi5qba/9ced8/7vHxLJMZKGQNQD4w4+qdraCNm0ujZjBkMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBQlbBtVTVkj4FKsACCkFEYNkY+e2TAfBgNVHSMEGDAWgBQAxZCSCaJg2IX5K3WtaKu270bZAjAKBggqhkjOPQQDAgNIADBFAiEAntq3a/mHhEm4b3T1ugHYaj+5C3TYbKZb3B9n2/TehoMCIB788ENp301qoydCN//rtY2BktHU+Td8SttYhxapPh79"
