---
# Proxmox NFS Mount Configuration

# TrueNAS Server IP
truenas_ip: "192.168.2.10"

# NFS Mount Points Configuration
nfs_mounts:
  - name: "postgresql"
    mount_origin: "/mnt/Data/postgresql"
    mount_point: "/mnt/postgresql"
    description: "PostgreSQL WAL Archive"

  - name: "git"
    mount_origin: "/mnt/Data/git"
    mount_point: "/mnt/git"
    description: "Git Repositories"

  - name: "gitlarge"
    mount_origin: "/mnt/Data/gitlarge"
    mount_point: "/mnt/gitlarge"
    description: "Git LFS Storage"
 
  - name: "objectstorage"
    mount_origin: "/mnt/Data/objectstorage"
    mount_point: "/mnt/objectstorage"
    description: "Object Storage"
  
  - name: "mongodb"
    mount_origin: "/mnt/Data/mongodb"
    mount_point: "/mnt/mongodb"
    description: "Mongo DB"

  - name: "observability"
    mount_origin: "/mnt/Data/observability"
    mount_point: "/mnt/observability"
    description: "Observability"

  - name: "artifact"
    mount_origin: "/mnt/Data/artifact"
    mount_point: "/mnt/artifact"
    description: "artifact"

ca : "MIIBqDCCAU6gAwIBAgIRAI47Wj+kveVYjlZnKAkshMQwCgYIKoZIzj0EAwIwMjETMBEGA1UEChMKSG9tZUxhYiBDQTEbMBkGA1UEAxMSSG9tZUxhYiBDQSBSb290IENBMB4XDTI2MDcwNDA4MjAzNVoXDTM2MDcwMTA4MjAzNVowMjETMBEGA1UEChMKSG9tZUxhYiBDQTEbMBkGA1UEAxMSSG9tZUxhYiBDQSBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEcyBfJOr9DpHEnTFxSKzcA+OpZ3foI5ZIL2VDo7oWAqyxdmaxb0T5MZMc4KTATTw/c6Vc3k9c5C72jpvXZulRIaNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYEFADFkJIJomDYhfkrda1oq7bvRtkCMAoGCCqGSM49BAMCA0gAMEUCIQDabIpH9ZBDRUpk0AcEikyuWdvI0hndsSPQQFgJ7ilmpwIgacI5p13BKMt4STfYwHQtKBbJPc43h5O8VHPS+Gy57W8="
