---
# Proxmox NFS Mount Configuration

# TrueNAS Server IP
truenas_ip: "192.168.2.10"

# NFS Mount Points Configuration
nfs_mounts:
  - name: "postgresql"
    mount_origin: "/mnt/Data/postgresql"
    mount_point: "/mnt/postgresql"
    description: "PostgreSQL WAL Archive"

  - name: "git"
    mount_origin: "/mnt/Data/git"
    mount_point: "/mnt/git"
    description: "Git Repositories"

  - name: "gitlarge"
    mount_origin: "/mnt/Data/gitlarge"
    mount_point: "/mnt/gitlarge"
    description: "Git LFS Storage"
 
  - name: "objectstorage"
    mount_origin: "/mnt/Data/objectstorage"
    mount_point: "/mnt/objectstorage"
    description: "Object Storage"
  
  - name: "mongodb"
    mount_origin: "/mnt/Data/mongodb"
    mount_point: "/mnt/mongodb"
    description: "Mongo DB"

  - name: "observability"
    mount_origin: "/mnt/Data/observability"
    mount_point: "/mnt/observability"
    description: "Observability"

  - name: "artifact"
    mount_origin: "/mnt/Data/artifact"
    mount_point: "/mnt/artifact"
    description: "artifact"

ca: "MIIBfTCCASSgAwIBAgIRAMcKgzsLznEw3o1SfgGe+yUwCgYIKoZIzj0EAwIwHTEbMBkGA1UEAxMSSG9tZUxhYiBDQSBSb290IENBMB4XDTI2MDcwNzE0MjE1NFoXDTQ2MDcwMjE0MjE1NFowHTEbMBkGA1UEAxMSSG9tZUxhYiBDQSBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEcjmPIh22QPl5EMKbosECZv3o2SlyKsLjJsRM/gxKM0dkUAt8ST5y6Ktx5GpLRzKksALUSA4lAhBupbmlp82xHaNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYEFOgEkRQrTPBndC6zBcAKpYXRGgbRMAoGCCqGSM49BAMCA0cAMEQCIF17Mf3R1DTnjuesqk4e3XqvPre3EU8kyR+OMhCDJ7UOAiARgFS6JSrt5rcDqMujnITs/nk4awz/ittbLOH4jfRAkQ=="
