---
# Role: Nginx
# Description: Nginx 리버스 프록시 + Certbot 자동 SSL 인증서 발급

galaxy_info:
  role_name: nginx
  author: cecil
  description: Nginx reverse proxy with automatic SSL certificate
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Alpine
      versions:
        - all

# 변수 구조
# Required Variables:
#   - postgres_ip: (string) PostgreSQL HAProxy IP 주소
#       예: "192.168.2.102"
#   - services: (list) 프록시할 서비스 목록
#       구조:
#         - domain: (string) 도메인 이름
#           ip: (string) 백엔드 IP
#           port: (int) 백엔드 포트
#       예: group_vars/nginx/var.yml 참조
#   - duckdns_token: (string) DuckDNS API 토큰 (vault.yml)
#
# Optional Variables: 없음
#
# Provided Variables:
#   - Nginx 리버스 프록시 (포트 80, 443)
#   - 자동 SSL 인증서 발급 (Certbot + DuckDNS)
#   - PostgreSQL 종료 프록시 (포트 5433 → 5432)
#
# 네트워크 요구사항:
#   - 포트 80 (HTTP)
#   - 포트 443 (HTTPS)
#   - 포트 5433 (PostgreSQL 프록시)
#   - 백엔드 서비스 접근 가능
#
# 중요 사항:
#   ⚠️ DuckDNS 토큰은 group_vars/nginx/vault.yml에서 정의
#   ⚠️ services 변수는 group_vars/nginx/var.yml에서 정의
#   ⚠️ 백엔드 서비스들이 실행 중이어야 합니다
#   ⚠️ SSL 인증서 갱신은 cron으로 자동화

# 의존성 설명
# - 선행 Role: Alpineupgrade
# - 후속 Role: 없음
# - 외부 의존성: 백엔드 서비스들 (Technitium, Portainer, HAProxy 등)
