- name: Setup Docker host
  become: true
  hosts: docker
  vars:
    subnet: 192.168.4.0/24
    gateway: 192.168.4.1
  roles:
    - docker

- name: Deploy Container
  become: true
  hosts: docker
  vars:
    portainer_ip: "192.168.4.2"
    glance_ip: "192.168.4.3"
    convertx_ip: "192.168.4.4"
    code_server_ip: "192.168.4.5"
    metube_ip : "192.168.4.6"
    searxng_ip: "192.168.4.7"
    searxng_secret_key: "{{ vault_searxng_secret_key }}"
    searxng_redis_password: "{{ vault_redis_password }}"
    technitium0_apikey: "{{ api1 }}"
    technitium1_apikey: "{{ api2 }}"
  roles:
    - portainer
    - glance
    - convertx
    - codeserver
    - metube
    - searxng
