- name: Etcd Configa and Set cert
  hosts: haproxy0
  become: true
  vars:
    etcd_member_index: 0
    server_name: "postgresql-haproxy.home.arpa"
  roles:
    - etcd_config
    - alpine_cert

- name: Etcd Config and Set cert
  hosts: db0
  become: true
  vars:
    etcd_member_index: 1
    server_name: "postgresql0.home.arpa"
  roles:
    - etcd_config
    - alpine_cert

- name: Etcd Config and Set cert
  hosts: db1
  become: true
  vars:
    etcd_member_index: 2
    server_name: "postgresql1.home.arpa"
  roles:
    - etcd_config
    - alpine_cert

- name: Install Etcd
  hosts: HApostgresql
  become: true
  roles:
    - etcd

- name: Patroni Config
  hosts: db0
  become: true
  vars:
    etcd_member_index: 1
  roles:
    - patroni_config

- name: Patroni Config
  hosts: db1
  become: true
  vars:
    etcd_member_index: 2
  roles:
    - patroni_config

- name: Install Postgresql and Patroni
  hosts: postgresql
  become: true
  roles:
    - postgresql
    - patroni

- name: Install haproxy and setup
  become: true
  hosts: haproxy0
  vars:
    etcd_member_index: 0
  roles:
    - haproxy0
