- name: Install Need Package
  ansible.builtin.apt:
    update_cache: false
    name:
      - certbot
      - ca-certificates
    state: present

- name: Add key group
  ansible.builtin.group:
    name: key
    state: present
    system: true

- name: Make certificate folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "755"
  loop:
    - /usr/local/share/ca-certificates
    - /etc/certificate/

- name: create ca.crt
  ansible.builtin.template:
    src: ca.crt.j2
    dest: /usr/local/share/ca-certificates/homelab-ca.crt
  register: cert_create

- name: Update CA store
  ansible.builtin.command: /usr/sbin/update-ca-certificates
  when: cert_create.changed

- name: Create certificate
  ansible.builtin.command:
    cmd: >
     certbot certonly
     --standalone
     --non-interactive
     --agree-tos
     --keep-until-expiring
     --email {{ acme_email }}
     --server {{ acme_server }}
     -d {{ server_name }}
     --config-dir /etc/certificate
     --work-dir /var/lib/certbot
     --logs-dir /var/log/certbot

- name: Make hook file
  ansible.builtin.template:
    src: key.sh.j2
    dest: /etc/certificate/renewal-hooks/deploy/key.sh
    mode: "755"

- name: Apply key group permissions
  ansible.builtin.command: /etc/certificate/renewal-hooks/deploy/key.sh

- name: Link certificate fullchain
  ansible.builtin.file:
    src: "/etc/certificate/live/{{ server_name }}/fullchain.pem"
    dest: /etc/certificate/certificate.crt
    state: link
    force: true

- name: Link certificate key
  ansible.builtin.file:
    src: "/etc/certificate/live/{{ server_name }}/privkey.pem"
    dest: /etc/certificate/certificate.key
    state: link
    force: true

- name: Link certificate chain 
  ansible.builtin.file:
    src: "/etc/certificate/live/{{ server_name }}/chain.pem"
    dest: /etc/certificate/chain.crt
    state: link
    force: true

- name: Configure certificate renewal 
  ansible.builtin.cron: 
    name: renew certificate
    minute: 0
    hour: "*/1"
    user: root
    job: >-
      REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      certbot renew -q 
      --config-dir /etc/certificate
      --work-dir /var/lib/certbot
      --logs-dir /var/log/certbot