- name: Install Need Package
  community.general.apk:
    update_cache: false
    name:
      - haproxy
      - rsyslog
    state: installed

- name: Add haproxy user to key group
  ansible.builtin.user:
    name: haproxy
    groups: key
    append: true

- name: Deploy HAProxy PEM renewal hook
  ansible.builtin.template:
    src: haproxy-pem.sh.j2
    dest: /etc/certificate/renewal-hooks/deploy/haproxy-pem.sh
    mode: "0755"

- name: Create HAProxy PEM
  ansible.builtin.command: /etc/certificate/renewal-hooks/deploy/haproxy-pem.sh

- name: Configure rsyslog for HAProxy
  ansible.builtin.blockinfile:
    path: /etc/rsyslog.conf
    block: |
      local2.* /var/log/haproxy.log
    marker: "# {mark} ANSIBLE MANAGED HAPROXY LOG"

- name: Create HAProxy log file
  ansible.builtin.file:
    path: /var/log/haproxy.log
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
    enabled: true

- name: Make Config file
  ansible.builtin.template:
    src: haproxy.j2
    dest: "/etc/haproxy/haproxy.cfg"
    mode: "755"
    force: true

- name: Start Haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
    enabled: true
