---
# Role: Docker
# Description: Docker 엔진 설치 및 macvlan 네트워크 설정

dependencies:
  - role: alpine_upgrade

galaxy_info:
  role_name: docker
  author: cecil
  description: Docker engine installation with macvlan network
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Alpine
      versions:
        - all

# 변수 구조
# Required Variables:
#   - subnet: (string) Docker macvlan 네트워크 대역 (예: "192.168.4.0/24")
#   - gateway: (string) Docker macvlan 게이트웨이 (예: "192.168.4.1")
#
# Optional Variables: 없음
#
# Provided Variables:
#   - Docker 엔진 실행
#   - docker_network (macvlan) 생성
#     - Parent interface: eth0
#     - Subnet: {{ subnet }}
#     - Gateway: {{ gateway }}
#
# 네트워크 요구사항:
#   - eth0 인터페이스가 존재해야 함
#   - macvlan 네트워크 대역이 라우팅 가능해야 함
#
# 중요 사항:
#   ⚠️ LXC 컨테이너에서 Docker를 실행하려면:
#      - EnableNesting: true
#      - EnableKeyctl: true
#   ⚠️ macvlan 네트워크는 컨테이너에게 직접 IP 할당
#   ⚠️ 호스트와 컨테이너 간 직접 통신 불가 (macvlan 특성)

# 의존성 설명
# - 선행 Role: Alpineupgrade
# - 후속 Role: Portainer, Glance (Docker 컨테이너 배포)
