- name: Install DNS
  hosts: dns
  become: true
  roles:
    - Alpineupgrade
    - Technitium

- name: Etcd Config
  hosts: haproxy
  become: true
  vars:
    etcd_member_index: 0
  roles:
    - EtcdConfig

- name: Etcd Config
  hosts: db0
  become: true
  vars:
    etcd_member_index: 1
  roles:
    - EtcdConfig

- name: Etcd Config
  hosts: db1
  become: true
  vars:
    etcd_member_index: 2
  roles:
    - EtcdConfig

- name: Install Etcd
  hosts: HApostgresql
  become: true
  roles:
    - Alpineupgrade
    - Etcd

- name: Patroni Config
  hosts: db0
  become: true
  vars:
    etcd_member_index: 1
    postgresql_version: 17
    subnet: "192.168.2.0/24"
    password: "{{ postgresql_password }}"
  roles:
    - PatroniConfig

- name: Patroni Config
  hosts: db1
  become: true
  vars:
    etcd_member_index: 2
    postgresql_version: 17
    subnet: "192.168.2.0/24"
    password: "{{ postgresql_password }}"
  roles:
    - PatroniConfig

- name: Install Postgresql and Patroni
  hosts: postgresql
  become: true
  roles:
    - Postgresql
    - Patroni

- name: Install haporxy and setup
  hosts: haproxy
  vars:
    etcd_member_index: 0
  roles:
    - Haproxy
