llama_version: "b8248"
llama_source_url: "https://github.com/ggml-org/llama.cpp/archive/refs/tags/{{ llama_version }}.tar.gz"
llama_source_checksum: ""
llama_cmake_jobs: 2
llama_cmake_flags:
  - -DGGML_VULKAN=ON
  - -DGGML_VULKAN_VALIDATE=OFF
  - -DLLAMA_OPENSSL=ON
  - -DGGML_LTO=ON
  - -DGGML_VULKAN_DEBUG=OFF
  - -DGGML_NATIVE=ON
  - -DGGML_OPENMP=ON

vulkan_headers_version: "v1.4.313"
vulkan_headers_checksum: ""
vulkan_hpp_checksum: ""
llama_port: 8080
llama_host: "0.0.0.0"
llama_gpu_layers: 50
llama_ctx_size: 256000
llama_model_file: "HauhauCS/Qwen3.5-9B-Uncensored-HauhauCS-Aggressive:Q4_K_M"
llama_server_extra_args:
  - --parallel
  - "2"
  - "--cache-type-k"
  - "q8_0"
  - "--cache-type-v"
  - "q8_0"
  - --flash-attn
  - "on"
  - --batch-size
  - "1024"
  - --ubatch-size 
  - "256"